spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ds0
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


    filters: stat,wall
    max-active: 12




  jdbc:
    template:
      query-timeout: 3

