server:
  port: 8006

spring:
  application:
    name: provider-payment06


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      #mysql驱动包
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  # consum配置
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}


#配置mybatis的xml
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.lquan.bean
