server:
  port: 8001


spring:
  application:
    name: provider-payment04


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      #mysql驱动包
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root



eureka:
  instance:
    hostname: provider04-payment
   # instance-id: provider04-payment8001

  client:
    register-with-eureka: true  #表示向注册中心注册自己
    fetch-registry: true   #表示可以在注册中心被检索到
    service-url:
      defaultZone: http://localhost:7001/eureka




#配置mybatis的xml
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.lquan.bean
