server:
  port: 81



spring:
  application:
    name: cusumer-order09-81

eureka:
  instance:
    hostname: cusumer09-order-81
    instance-id: cusumer09-order81

    lease-renewal-interval-in-seconds: 30  #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
    lease-expiration-duration-in-seconds: 90   #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒


  client:
    register-with-eureka: true  #表示向注册中心注册自己
    fetch-registry: true   #表示可以在注册中心被检索到
    service-url:
      defaultZone: http://eureka7001:7001/eureka
      #defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka,http://eureka7003:7003/eureka


feign:
  hystrix:
    enabled: true