spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ds0
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      aop-patterns: com.lquan.boot.*   #监控SpringBean
      filters: stat,wall,slf4j # 底层开启功能，stat（sql监控），wall（防火墙）、日志

      stat-view-servlet:   # 配置监控页功能
        enabled: true  #配置druid的监控页面功能开启，默认关闭的
        login-username: admin  #登录名
        login-password: admin  #登录密码
        reset-enable: false  #监控页面上的重置按钮是否隐藏，默认是有的按钮的

      web-stat-filter:  # 监控web
        enabled: true
        url-pattern: /*  #拦截所有
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'  # 排除




      filter:    # 对上面filters里面的stat的详细配置
        stat:     #sql监控
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true

        wall:         #防火墙
          enabled: true
          config:
            drop-table-allow: false
