server:
  port: 7003




eureka:
  instance:
    hostname: eureka7003  #eureka服务端的实例名字

  client:
    register-with-eureka: false #不把自己作为一个客户端注册到自己身上

    fetch-registry: false  #不需要从服务端获取注册信息（因为在这里自己就是服务端，而且已经禁用自己注册了），并不需要检索服务
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址

  server:
    enable-self-preservation: false #关闭自我保护机制
    eviction-interval-timer-in-ms: 4000 #设置清理问题间隔时间


spring:
  application:
    name: cluster-eureka-7003
