server:
  port: 9528

spring:
  application:
    name: cloud-gateway-9528


  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
        #  uri: http://127.0.0.1:8001/
          uri: lb://provider-payment11  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**  #断言,路径相匹配的进行路由


        - id: payment_routh2 #路由的ID，没有固定规则但要求唯一，建议配合服务名
       #   uri: http://127.0.0.1:8001/
          uri: lb://provider-payment11   #需要注意的是uri的协议为lb，表示启用Gateway的负载均衡功能。
          predicates:
            - Path=/payment/lb/**  #断言,路径相匹配的进行路由




eureka:
  instance:
    instance-id: cloud-gateway-service-9528  #微服务的主机名
    hostname: cloud-gateway-service
    prefer-ip-address: true

    lease-renewal-interval-in-seconds: 30  #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
    lease-expiration-duration-in-seconds: 90   #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒


  client:
    register-with-eureka: true  #表示向注册中心注册自己
    fetch-registry: true   #表示可以在注册中心被检索到
    service-url:
      defaultZone: http://eureka7001:7001/eureka
      #defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka,http://eureka7003:7003/eureka

