server:
  port: 8001


spring:
  application:
    name: provider-payment07


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      #mysql驱动包
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root



eureka:
  instance:
 #   hostname: provider04-payment8002
    instance-id: provider07-payment8001  #微服务的主机名
    prefer-ip-address: true

  client:
    register-with-eureka: true  #表示向注册中心注册自己
    fetch-registry: true   #表示可以在注册中心被检索到
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka,http://eureka7003:7003/eureka




#配置mybatis的xml
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.lquan.bean
