server:
  port: 7002

eureka:
  instance:
    hostname: erureka7002  #eureka服务端的实例名字
    prefer-ip-address: false

  client:
    register-with-eureka: false #表示不向注册中心注册自己  register with 向……注册登记
    fetch-registry: false  #表示自己就是注册中心，职责是维护服务实例，并不需要检索服务 fetch 获取的
    service-url:
        defaultZone: http://eureka7001:7001/eureka/,http://eureka7003:7003/eureka/    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址

  server:
    eviction-interval-timer-in-ms: 4000 #清理的间隔时间
    enable-self-preservation: false  #关闭自我保护机制


spring:
  application:
    name: cluster-eureka-7002